# log
logging:
  file:
    path: ./log/
    name: ./log/output.log
  level:
    root: info

# bot
bot:
  creator: 5006320370
  token: 6097531887:AAGDY2CcBSMrFprKpl7EB0UJM93-GzxyRjI

# elasticsearch
elastic:
  hostname: 127.0.0.1
  schema: http
  port: 9900

# 代理
proxy:
  enabled: true
  type: SOCKS
  ip: 127.0.0.1
  port: 7890

# 索引公告频道id
channel:
  bulletin:
    id: -1001707221406
# 审核群组id
group:
  approve:
    id: -1001153444411
secretary:
  # 群组中BOT消息自销毁周期
  # 单位：秒
  autoDeleteMsgCycle: 30
  list:
    # 每页多少条
    size: 30
  memory:
    # 内存中暂存多少秒
    cycle: 30
    # 内存中暂存多少条，用于提升响应效率
    size: 100
  # 用于更新频道人数的 bot
  # 由于收录频道无需将bot添加至频道中，因此，需要bot来获取
  # 每个 bot 每天只能通过 telegram api 获取 200 个 频道/群组 的信息
  # 我们可能收录数千万个频道，因此，我们需要更多的 bot
  poppy-bot: >
    2095585004:AAGbZknO87JNCB1mvE8BXY6LVaH0u7pAmy8,
    2021973345:AAHA6V91BwOfDMDnKnHeH4HzwjvgwrXwNxI,
    2078724060:AAFK6ee1NEMc-RokMkFazojyrgvrBpRXLF8,
    1913773538:AAHVV-9RDHvdtaDL7zKF0rfdK-9dD-XJmzE,
    1995573135:AAFYD7aZAiFRYHfLHfaUB0u9zA0HnGVo7hY,
    1986552287:AAHfYRHeog51A1gtBgWRUQTgJgLzRGENDrg,
    1990812021:AAHyW8xkU6T1-eyQo_k2Y_MmhOFezulJ_ns,
    1977545956:AAGJosRLA894GYsGQoDyqXiW1q3hpTFeB3U,
    1980605731:AAFhl8Cr1f87LUdPuzskjNfO40Q16K0RQsI,
    2007581273:AAH9DOdCJDkA8AISK64c_8y5VKSsGyXMhiE,
    2064764705:AAHybpgGJlaYv2jbLCTdgLJSuwAJ0YMDfD8,
    2080324455:AAECIcI9x9Rl3flmVkA7c0XDs3EOzRxp-7Q
user:
  footprint:
    # N秒内记录一次用户，用户统计用户总量、日增、日活
    cycle: 600
