# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          cd index-bot
          chmod +x gradlew
          ./gradlew bootJar

      - name: Download resource
        run: |
          mkdir resource
          cd resource
          curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.2-linux-x86_64.tar.gz
          curl -O https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.15.2/elasticsearch-analysis-ik-7.15.2.zip
          curl -O https://cloud.scomarlf.com/api/v3/file/download/2mM83NmzjtdVetKg?sign=DVRtoH0gYfGAvridR9lHLt4DLhJNjhteI-W3On4jhdE%3D%3A1637573022
          ls

      - name: Move files
        run: |
          mkdir -p artifacts
          mv package/lang artifacts/
          mv package/data artifacts/
          mv index-bot/build/libs/telegram-index-bot-2.0.0.jar artifacts/
          mv index-bot/src/main/resources/application.properties artifacts/

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: telegram-index-bot
          path: artifacts/*
